export const API_ROLES = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  OPS_USER: 'OPS_USER',
  ADMIN: 'ADMIN',
  EDITOR: 'EDITOR',
  VIEWER: 'VIEWER',
  OPS: 'OPS',
} as const;

export const NAV_ROLES = [
  'ADMIN',
  'NAV_ADMIN',
  'NAV_ADMINISTRATOR',
  'NAV_MANAGEMENT',
  'OPS_MANAGEMENT',
  'ADMIN_MANAGEMENT',
  'OPS_USER',
  'ADMIN_USER',
  'EXT_USER',
] as const;
